[project]
authors = ["longred <zch774931894@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "OminiControl"
platforms = ["linux-64"]
version = "0.1.0"

[pypi-options]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[tasks]

[system-requirements]
cuda = "12.4"

[dependencies]
python = { version = "==3.12.7" }
cudnn = ">=9"

[pypi-dependencies]
torch = { version = "==2.5.1+cu124", index = "https://download.pytorch.org/whl/cu124" }
torchvision = { version = "*", index = "https://download.pytorch.org/whl/cu124" }
xformers = { version = "*", index = "https://download.pytorch.org/whl/cu124" }
transformers = "*"
diffusers = "*"
peft = "*"
opencv-python = "*"
protobuf = "*"
sentencepiece = "*"
gradio = "*"
jupyter = "*"
torchao = "*"
